### ISSUE TITLE
Don't ever use http urls

### ISSUE THREAD

**Issue by nskinkel** [Senior-Design-May1601/config#27]
We should **never** use `http://` when urls are hardcoded. **ALWAYS** use `https://`. Every play needs to be checked for this -- at least a few (e.g. the splunk install role) use hardcoded `http://`

**Comment by dborg92** [comment]
simply attempting to switch to https: produces the following warning:fatal: [splunk]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for download.splunk.com:443. Make sure your managed systems have a valid CA certificate installed.  If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine.  You can use validate_certs=False if you do not need to confirm the server\s identity but this is unsafe and not recommended Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Comment by dborg92** [comment]
i'm not familiar with the process to get an https url for these downloads.

**Comment by nskinkel** [comment]
Works fine for me on my machine. Include more info:
1. What machine is giving you this error? Your laptop? A vm? Over vagrant?
2. What distro/os version is doing this?
3. What version of Python do you have? The error clearly says you need >= 2.7.9 if they're using SNI.

etc.

We **cannot** use plain `http://` urls to download things so this has to be fixed.

**Comment by jonhope3** [comment]
Switched to using get_url, closing the issue.
