### ISSUE TITLE
Make start-service role idempotent

### ISSUE THREAD

**Issue by nskinkel** [Senior-Design-May1601/config#36]
This role shouldn't need to check if a file exists.

**Comment by dborg92** [comment]
currently I believe there is a bug in my version of Ansible. If anyone else is able to run this role successfully without checking for this please let me know. I'll look into updating my ansible version to hopefully fix this soon.

**Comment by dborg92** [comment]
upgrading to ansible v 2.0.2 fixed this bug. Role is back to being idempotent.
