### ISSUE TITLE
IPtables block Out 123

### ISSUE THREAD

**Issue by dborg92** [Senior-Design-May1601/config#40]
When starting projectmain, port 8080 is unreachable with current iptables loaded. 
cat //var/log/kern.log shows iptables dropped for 

Apr  4 12:03:27 localhost kernel: [  784.458687] IPTables-Dropped: IN= OUT=eth0 SRC=10.0.2.15 DST=66.79.136.235 LEN=76 TOS=0x00 PREC=0xC0 TTL=64 ID=63011 DF PROTO=UDP SPT=123 DPT=123 LEN=56

Do we need to open access to this output port?

**Comment by nskinkel** [comment]
Oh right, that's for [ntp](https://en.wikipedia.org/wiki/Network_Time_Protocol). Add this rule:

```
iptables -A OUTPUT -p udp --sport 123 --dport 123 -j ACCEPT
```
