### ISSUE TITLE
Make an "add-plugin" role

### ISSUE THREAD

**Issue by nskinkel** [Senior-Design-May1601/config#42]
We need an "add-plugin" role that should do the following things (it should cannabalize from other, existing roles when possible):
1. Create an unprivileged user for the plugin being installed
2. Add the new user to the plugin group
3. Install any plugin dependencies
4. Clone, build, and install the plugin
5. Make the binary executable by users of the group from (2)
6. Copy the config file for the plugin, if any, to the correct /etc location
7. Add a correct systemd file for the plugin with the user from (2)
8. Start the plugin

**Comment by dborg92** [comment]
does the above imply creating/starting a unit file for each plugin?

**Comment by nskinkel** [comment]
Ah, oops. I made a mistake, you're right. Will comment more when I have time.
